animal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("petsansar.urls")),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

petsansar/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Contact(models.Model):
    contact_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    desc = models.TextField(max_length=500)
    phonenumber = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Animal(models.Model):
    animal_id = models.AutoField
    animaltype = models.CharField(max_length=50, default="")
    breeds = models.CharField(max_length=50, default="")
    color = models.CharField(max_length=10, default="")
    eyecolor = models.CharField(max_length=10, default="")
    desc = models.TextField(max_length=100, default="")
    DOB = models.DateField()
    sex = models.CharField(max_length=8, default="")
    weight = models.IntegerField()
    medical_condition = models.CharField(max_length=10, default="")
    location = models.CharField(max_length=50, default="")
    available_for_adoption = models.BooleanField(default=True)
    image = models.ImageField(upload_to='adopt/images')
    adopted = models.BooleanField(default=False)

    def __str__(self):
        return self.breeds


class Surrender(models.Model):
    animal_id = models.AutoField
    animaltype = models.CharField(max_length=50, default="")
    breeds = models.CharField(max_length=50, default="")
    color = models.CharField(max_length=10, default="")
    desc = models.TextField(max_length=100, default="")
    DOB = models.DateField()
    sex = models.CharField(max_length=8, default="")
    weight = models.IntegerField()
    medical_condition = models.CharField(max_length=10, default="")
    medical_certificate=models.ImageField(upload_to="img/%y",blank="True", null="True")
    location = models.CharField(max_length=200, default="")
    is_approved = models.BooleanField(default=False)
    image = models.ImageField(upload_to="img/%y")

    def __str__(self):
        return self.breeds


class Donation(models.Model):
    donation_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    phonenumber = models.IntegerField()
    desc = models.TextField(max_length=500)

    def __str__(self):
        return self.name


class Strayanimal(models.Model):
    strayanimal_id = models.AutoField(primary_key=True)
    description = models.TextField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    image = models.ImageField(upload_to="img/%y")

    def __int__(self):
        return self.id


class RescueLocation(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name


class Strayanimalrescue(models.Model):
    name = models.CharField(max_length=100)
    phone = models.TextField(max_length=10)
    location = models.CharField(max_length=200)
    latitude = models.FloatField()
    longitude = models.FloatField()
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to="img/%y")
    date_reported = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class AdoptionRequest(models.Model):
    ADOPTION_STATUS = (
        ("pending", "pending"),
        ("rejected", "rejected"),
        ("Accepted", "Accepted"),
        ("Not Available","Not Available"),
    )
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name="adoption_requests")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="adoption_requests")
    contact = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    description = models.TextField(max_length=100, null=True, blank=True)
    status = models.CharField(choices=ADOPTION_STATUS, default='pending', max_length=20)

    def __str__(self):
        return f"Adoption Request for {self.animal.breeds}"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    adoption_request = models.ForeignKey('AdoptionRequest', on_delete=models.CASCADE)


class ListAdoptionRequest(models.Model):
    ADOPTION_STATUS =(
    ("pending", "pending"),
    ("rejected", "rejected"),
    ("Accepted", "Accepted"),
    ("Not Available","Not Available"),
)
    pet = models.ForeignKey(Surrender, on_delete=models.CASCADE, related_name="list_requests")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="list_requests")
    contact= models.TextField(null=True, blank=True)
    address= models.TextField(null=True, blank=True)
    description = models.TextField(max_length=100, null=True, blank=True)
    status = models.CharField(choices=ADOPTION_STATUS, default='pending', max_length=20)

    def __str__(self):
        return f"adoption Request for {self.pet.breeds}"

templates/activatefail.html
<h1>Something went wrong </h1>

templates/adoption_map.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Animal adoption map</title>
</head>

<body>
    <div id="map" style="height:500px"></div>
    <script>
        function initmap() {
            var mapCenter = { lat: 40.7128, lng: -74.0060 };
            var map = new google.maps.Map(document.getElementById('map'), {
                center: mapCenter,
                zoom: 8
            });
        }
        var animals = '{{ animals| safe }}';
        for (var i = 0; i < animals.length; i++) {
            var animal = animals[i];
            var marker = new google.maps.Marker({
                position: { lat: animal.latitude, lng: animal.longitude },
                map: map,
                title: animal.name
            });
        }
    </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&callback=initMap"></script>

</body>

</html>

templates/adoption_request.html
{% extends 'base.html' %}

{% block title %} Adoption Request Form {% endblock %}

{% block content %}

{% endblock content %}

{% block body %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-8">
        <form method="post" action="{% url 'submit_adoption_request' animal.id %}" class="form"
            style="margin-left: auto; margin-right: auto;">
            {% csrf_token %}
            <div class="container p-4 ">
                <h3 class="pb-4 "><u>Adoption Form</u></h3>
                <div class="m-1">
                    <label for="breeds">Breeds: </label>
                    <input type="text" name="breeds" id="breeds" value="{{animal.breeds}}" class="form-control p-1 rounded w-25"
                        readonly>
                </div>
                <div class="m-1">
                    <label for="breeds">Colour: </label>
                    <input type="text" name="colour" id="colour" value="{{animal.color}}" class=" form-control p-1 rounded w-25"
                        readonly>
                </div>
                <div class="m-1">
                    <label for="breeds">Sex: </label>
                    <input type="text" name="sex" id="sex" value="{{animal.sex}}" class=" form-control p-1 rounded w-25"
                        readonly>
                </div>
                <div class="m-1">
                    <label for="medical_condition">Medical Condition: </label>
                    <input type="text" name="medical_condition" id="medical_condition" value="{{animal.medical_condition}}"
                        class=" form-control p-1 rounded w-25" readonly>
                </div>
                <div class="m-1">
                    <label for="location">Location: </label>
                    <input type="text" name="location" id="location" value="{{animal.location}}"
                        class=" form-control p-1 rounded w-25" readonly>
                </div>
                <div class="m-1">
                    <label for="desc">Description: </label>
                    <p class=" form-control p-1 rounded w-25"  type="text" name="desc" id="desc">{{animal.desc}}</p>
                </div>
                <div class="m-1">
                    <label for="desc">Your Username: </label>
                    <p class=" form-control p-1 rounded w-25"  type="text" name="desc" id="desc">{{user.username}}</p>
                </div>

                <div class="m-1">
                    <label for="desc">Your Email: </label>
                    <p type="text" name="desc" id="desc">{{user.email}}</p>
                </div>
                <div class="m-1">
                    <label for="location">Enter your contact number: </label>
                    <input type="number" name="contact" id="contact" class=" form-control p-1 rounded w-25" required>
                </div>
                <div class="m-1">
                    <label for="location">Enter your address: </label>
                    <input type="text" name="address" id="address" class=" form-control p-1 rounded w-25" required>
                </div>
                <div class="m-1">
                    <label for="description">Write some description: </label>
                    <input name="description" id="description" class="form-control p-1 rounded w-25" required>
                </div>
                <input type="submit" value="Adopt" class=" btn btn-secondary mt-4">
            </div>
        </form>
    </div>
    <div class="col-md-1"></div>

</div>



{% endblock body %}

templates/animaldetails.html
{% extends 'base.html' %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-3 mt-3">
                <img src="/media/{{animal.image}}" class="card-img-top" alt="" height="200" width="150">
                <div class="card-body">
                    <h1>{{ animal.breeds }}</h1><br><br>
                    <h5 class="card-title mt-2" id="namepet{{animal.id}}"><span>Type:</span>{{animal.animaltype}}</h5>
                    <h5 class="card-text">Color:{{animal.color}}</h5>
                    <h6 class="card-title">
                        <span id="dobpet{{i.id}}">DOB:{{animal.DOB}}</span>
                    </h6>
                    <p class="card-text" style="font-weight: bold;"> Description: {{animal.desc}}</p>
                    <h5 class="card-text">Weight:{{animal.weight}} kg</h5>
                    <h5 class="card-text">Medical_condition:{{animal.medical_condition}}</h5>
                    <h5 class="card-text">Location:{{animal.location}}</h5>
                      
                    <!-- <span id="divpr{{i.id}}" class="divpr">     
                          <button type="submit"  class="btn btn-danger "> Adopt</button></a>
                        </span> -->
                        <button type="btn btn-info"> <a href="{% url 'adoption_request' animal.id %}">Adopt</a></button>

                </div>
            </div>
        </div>
    </div>


{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Petsansar -
        {% block title %} {% endblock %}
    </title>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

</head>
<style>
    footer {
        width: auto;
        height: auto;
    }
</style>

<body>

    <div class="" style="background-image: url('/static/images/Banner_01.jpg');
                            height: 100vh no-repeat">

        <nav class="navbar navbar-fixed-top navbar-expand-lg p-2 text-secondary  " style="font-size: 16pt;">
            <div class="container-fluid">
                <a class="navbar-brand" href="/"><img src="{% static '/images/a.jpg' %}" alt=" " height="70px"
                        width="90px" bg-dark></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/blog">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contact">Contact</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/list">List </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'surrender' %}">Surrender </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'adoption_stats' %}">statistics </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'surrender_stats' %}">Surrender-Statics </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rescue_form' %}">Rescue/Shelter </a>
                        </li>



                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'view_notifications' %}">
                                <span class="badge bg-danger">
                                    {% if user.is_authenticated %}
                                    {{ user.notification_set.count }}
                                    {% else %}
                                    0
                                    {% endif %}
                                </span>
                                <i class="fa fa-bell text-danger" aria-hidden="true"></i>
                            </a>
                        </li>



                        <li class="nav-item"><a class="nav-link" href="/logout" class="btn btn-primary">Logout</a></li>

                        {% else %}

                        <li class="nav-item">
                            <a class="nav-link" href="/signup">signup </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Login</a>
                        </li>


                        {% endif %}


                    </ul>

                    <form action="{% url 'search' %}" method="GET" class="d-flex" role="search">
                        <input class="form-control me-2" type="search" name="query" placeholder="Search"
                            aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row justify-content-start">
                <div class="col-12 col-lg-7">

                    <h1
                        class="mbr-section-subtitle mbr-fonts-style mt-lg-4 display-2 text-black text-light-emphasis  p-3">
                        <strong>
                        </strong>
                        <div class="text-gray"><strong>Adopting is Better Than Buying </strong></div>
                    </h1>
                    <p class="mbr-text mbr-fonts-style display-7" style="font-size: 16pt;">
                        Pet adoption is the process of transferring responsibility for a pet that was previously owned
                        by another party. Common
                        sources for adoptable pets are animal shelters, rescue groups, or other pet owners.
                    </p>
                    <div class="mbr-section-btn custom-section-btn"> <button type="button" class="btn btn-primary"><a
                                class="btn btn-primary text-white display-7" href="/donation">
                                Donate
                            </a></button></div>
                </div>
            </div>
        </div>
    </div>

    <!-- alert message -->

    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show">
        <strong></strong>{{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
    {% endfor %}
    <!-----animal banner------->


    <div class="mbr-overlay" style="opacity: 0.1; background-color: rgb(33, 36, 40);"></div>

    </div>



    {% block content %}


    {% endblock content %}

    {% block body %}



    {% endblock body %}

    {% block gallery %}

    {% endblock gallery %}

    {% block blog %}



    {% endblock blog %}

    {% block statistics %}
    {% endblock statistics %}


    <!-- Footer -->
    <footer class=" mt-5 text-lg-start bg-dark text-white max-width: 100%; ">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Links -->
            <section class="">
                <!--Grid row-->
                <div class="row">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                        <h6 class="text-uppercase mb-4 font-weight-bold">
                            Petsansar
                        </h6>
                        <p>Pet Sansar usually refers to the process of taking guardianship of and responsibility for a
                            pet that a previous owner
                            has abandoned or released to a shelter</p>
                    </div>
                    <!-- Grid column -->

                    <hr class="w-100 clearfix d-md-none" />

                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                        <h6 class="text-uppercase mb-4 font-weight-bold">Quick Links </h6>
                        <a class="class=" text-lg text-teal-500 hover:text-teal-700""
                            href="{% url 'blog' %}">Blog</a><br>
                        <a class="class=" text-lg text-teal-500 hover:text-teal-700""
                            href="{% url 'surrender' %}">Surrender</a><br>
                        <a class="dclass=" text-lg text-teal-500 hover:text-teal-700""
                         href="{% url 'list' %}">List of
                            surrender animal</a><br>
                        <a class="dclass=" text-lg text-teal-500 hover:text-teal-700""
                         href="{% url 'donation' %}">
                            Donate</a>

                    </div>
                    <!-- Grid column -->

                    <hr class="w-100 clearfix d-md-none" />

                    <!-- Grid column -->
                    <hr class="w-100 clearfix d-md-none" />

                    <!-- Grid column -->


                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                        <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>

                        <!-- Facebook -->
                        <a class="btn btn-primary btn-floating m-1" style="background-color: #3b5998" href="#"
                            role="button"><i class="fab fa-facebook-f"></i></a>

                        <!-- Twitter -->
                        <a class="btn btn-primary btn-floating m-1" style="background-color: #55acee" href="#"
                            role="button"><i class="fab fa-twitter"></i></a>


                        <!-- Instagram -->
                        <a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac" href="#"
                            role="button"><i class="fab fa-instagram"></i></a>

                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                        <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
                        <p>When you want to know more about us contact us for more details </p>
                        <a href="{% url 'contact' %}"><button type="buton" class="btn btn-primary">Contact us</button>
                        </a>
                    </div>
                    <!-- Grid column -->
                </div>
                <!--Grid row-->
            </section>
            <!-- Section: Links -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            © 2020 Copyright:
            <a class="text-white" href="/">Pet Sansar</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
</body>

</html>

templates/dog.html
{% extends 'base.html' %}
{% block title %}Dog {% endblock %}
{% block body %}
<div class="container">
<h1 class="text-center">Details of Dog</h1>
 <div>  
    <img src="static/images/slide1.jpg" class="img-fluid" />
 </div>
 <h3 class=" text-dark mt-5" style="padding-left: 1px;" >About Dog </h3>
 <p >Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis delectus 
    exercitationem esse saepe eius omnis, dicta, labore cupiditate vitae reiciendis, 
    eum sequi est aspernatur? Architecto reiciendis et laudantium voluptates nesciunt 
    corrupti, nam quas excepturi tempora maxime quidem aliquam? Veritatis officiis numquam
     fuga sunt libero. Rem ex ut aperiam incidunt aliquam minus iure minima saepe mollitia 
     voluptates explicabo ad, natus ipsa doloremque vel dolore laboriosam maiores similique.
      Placeat consequatur, explicabo porro totam dolorum consectetur amet atque sit rerum a 
      tempora eaque, maxime quaerat id? Assumenda, distinctio, quam dolor quibusdam qui totam,
       fugit porro a minus maiores sit modi illum sunt consequuntur laudantium mollitia accusantium
        dignissimos! Vero porro, repudiandae placeat ea asperiores nihil beatae expedita 
    voluptatem nesciunt a, ad veniam fugit natus perspiciatis, maiores architecto.</p>
</div> 
<h2 class="text-center text-danger mt-5">Feeding tips </h2>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-4 mt-5 p-5"> <img src="static/images/12.jpg" class="img-fluid" alt="Sample image"></div>

        <div class="col-md-8 mt-5">
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem id placeat reprehenderit deleniti
                ducimus commodi
                nesciunt, fugit qui accusamus cumque cum beatae? Temporibus voluptates cupiditate autem aut. Totam
                deserunt error
                voluptates nemo numquam, cupiditate ipsa vitae eos voluptate assumenda autem placeat iste vero tempore
                quae optio
                possimus nulla dicta facilis explicabo. Nobis, tenetur dolorum? Odit quas necessitatibus numquam ratione
                possimus.
                Delectus, aperiam harum quidem ab adipisci assumenda velit ducimus itaque! Assumenda quas impedit fuga.
                Vitae nam
                error quos placeat inventore facilis fugit soluta. Consequuntur odio ullam perferendis, veniam
                dignissimos quos iste
                dicta. Corporis, molestiae vero. Incidunt possimus eaque soluta libero temporibus nostrum dignissimos
                omnis tempora
                laboriosam consequuntur doloremque optio quas id neque, ratione, hic aliquid praesentium iste facere?
                Eos, laborum!
            </p>
        </div>
    </div>
</div>

<h3 style="padding-left: 15%;" class="mt-5">Caring Tips </h3>
<div class="container mt-4">
    <div class="row">

        <div class="col-md-8 mt-2">
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem id placeat reprehenderit deleniti
                ducimus commodi
                nesciunt, fugit qui accusamus cumque cum beatae? Temporibus voluptates cupiditate autem aut. Totam
                deserunt error
                voluptates nemo numquam, cupiditate ipsa vitae eos voluptate assumenda autem placeat iste vero tempore
                quae optio
                possimus nulla dicta facilis explicabo. Nobis, tenetur dolorum? Odit quas necessitatibus numquam ratione
                possimus.
                Delectus, aperiam harum quidem ab adipisci assumenda velit ducimus itaque! Assumenda quas impedit fuga.
                Vitae nam
                error quos placeat inventore facilis fugit soluta. Consequuntur odio ullam perferendis, veniam
                dignissimos quos iste
                dicta. Corporis, molestiae vero. Incidunt possimus eaque soluta libero temporibus nostrum dignissimos
                omnis tempora
                laboriosam consequuntur doloremque optio quas id neque, ratione, hic aliquid praesentium iste facere?
                Eos, laborum!
            </p>
        </div>
                <div class="col-md-4 mt-5 p-5"> <img src="static/images/12.jpg" class="img-fluid" alt="Sample image"></div>

    </div>
</div>
{% endblock body%}

templates/list.html
{% extends 'base.html' %}
{% block title %}List of surrender animal {% endblock %}

{% block body %}

<div class="section_title">
    <h2 class="text-center m-2 md-3">Welcome to my Pet Adoption Website </h2>
    <h3 class="text-center"> Check Ours <span class="text-danger">Animals</span></h3>
    <div class="container mt-2">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                    Illum soluta, distinctio inventore repudiandae ullam assumenda debitis numquam fuga dolorem vero
                    fugiat blanditiis itaque exercitationem tenetur corporis accusantium suscipit atque vel.
                </p>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% for pet in pets %}

            <div class="col-md-3 mt-3">
                {% if pet.image %}
                <img src="{{pet.image.url}}" alt="" weidth="100" height="150">
                <img src="{{pet.mcertificate.url}}" alt=""  weidth="50" height="50" class="p-2" >

                {% else %}
                <!-- <img src="/media/{{pet.image}}" alt=""> -->
                {% endif %}


                <div class="card-body" style="font-weight: bold; text-transform: capitalize;">
                    <p> animaltype:{{ pet.animaltype }}</p>
                    <p>Breeds:{{pet.breeds}}| Color:{{pet.color}}</p>
                    <p></p>
                    <p>Description:{{pet.desc}}</p>
                    <p>Date of Birth:{{pet.DOB}}| Sex:{{pet.sex}}</p>
                    <p></p>
                    <p>Weight:{{pet.weight }} kg |</p>
                    <p>Medical_Condition:{{pet.medical}}</p>
                    <p></p>
                    <p>Location:{{pet.location}}</p>


                    <button><a href="{% url 'list_request' pet.pk %}">Adopt</a></button>


                    <a href="/media/{{pet.medical_certificate}}">
                        <button class="btn btn-success btn-sm cart">View</button>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endblock body %}

templates/thankyou.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2 style="font-size: larger;"> Thank You for Submitting the Stray Animal Rescue Form! </h2>
</body>
</html>